"""solicitudes_pedido

Revision ID: 6e2ca2625be8
Revises: a7422f55ba29
Create Date: 2026-07-10 11:31:54.854939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e2ca2625be8'
down_revision = 'a7422f55ba29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solicitudes_pedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('cliente_nombre', sa.String(length=80), nullable=False),
    sa.Column('cliente_email', sa.String(length=120), nullable=False),
    sa.Column('cliente_telefono', sa.String(length=20), nullable=True),
    sa.Column('cliente_direccion', sa.String(length=255), nullable=True),
    sa.Column('cliente_ciudad', sa.String(length=80), nullable=True),
    sa.Column('productos_json', sa.JSON(), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('estado', sa.Enum('PENDIENTE', 'APROBADO', 'RECHAZADO', name='estadosolicitud'), nullable=False),
    sa.Column('motivo_rechazo', sa.String(length=255), nullable=True),
    sa.Column('atendido_por_id', sa.Integer(), nullable=True),
    sa.Column('venta_id', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_atencion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['atendido_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['venta_id'], ['ventas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('solicitudes_pedido', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_solicitudes_pedido_codigo'), ['codigo'], unique=True)
        batch_op.create_index(batch_op.f('ix_solicitudes_pedido_fecha_creacion'), ['fecha_creacion'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitudes_pedido', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_solicitudes_pedido_fecha_creacion'))
        batch_op.drop_index(batch_op.f('ix_solicitudes_pedido_codigo'))

    op.drop_table('solicitudes_pedido')
    # ### end Alembic commands ###
