"""Modelos iniciales

Revision ID: a7422f55ba29
Revises: 
Create Date: 2026-07-09 19:43:08.236383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7422f55ba29'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('categoria_padre_id', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_padre_id'], ['categorias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categorias_nombre'), ['nombre'], unique=True)

    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('apellido', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('dni_ruc', sa.String(length=15), nullable=True),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('ciudad', sa.String(length=80), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clientes_dni_ruc'), ['dni_ruc'], unique=True)
        batch_op.create_index(batch_op.f('ix_clientes_email'), ['email'], unique=True)

    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_nombre'), ['nombre'], unique=True)

    op.create_table('productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=30), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('marca', sa.String(length=60), nullable=True),
    sa.Column('modelo', sa.String(length=60), nullable=True),
    sa.Column('imagen_url', sa.String(length=255), nullable=True),
    sa.Column('precio_compra', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('precio_venta', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('stock_actual', sa.Integer(), nullable=False),
    sa.Column('stock_minimo', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.CheckConstraint('precio_venta >= 0', name='ck_producto_precio_venta_positivo'),
    sa.CheckConstraint('stock_actual >= 0', name='ck_producto_stock_no_negativo'),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.create_index('ix_productos_categoria_activo', ['categoria_id', 'activo'], unique=False)
        batch_op.create_index(batch_op.f('ix_productos_nombre'), ['nombre'], unique=False)
        batch_op.create_index(batch_op.f('ix_productos_sku'), ['sku'], unique=True)

    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('apellido', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('ultimo_login', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_email'), ['email'], unique=True)
        batch_op.create_index('ix_usuarios_email_activo', ['email', 'activo'], unique=False)

    op.create_table('auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('accion', sa.String(length=20), nullable=False),
    sa.Column('tabla_afectada', sa.String(length=60), nullable=False),
    sa.Column('registro_id', sa.Integer(), nullable=True),
    sa.Column('datos_anteriores', sa.JSON(), nullable=True),
    sa.Column('datos_nuevos', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auditoria', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auditoria_fecha'), ['fecha'], unique=False)
        batch_op.create_index(batch_op.f('ix_auditoria_tabla_afectada'), ['tabla_afectada'], unique=False)

    op.create_table('movimientos_inventario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('ENTRADA', 'SALIDA', 'AJUSTE', name='tipomovimiento'), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('stock_anterior', sa.Integer(), nullable=False),
    sa.Column('stock_nuevo', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.String(length=255), nullable=True),
    sa.Column('referencia', sa.String(length=50), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.CheckConstraint('cantidad > 0', name='ck_movimiento_cantidad_positiva'),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('movimientos_inventario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_movimientos_inventario_fecha'), ['fecha'], unique=False)
        batch_op.create_index('ix_movimiento_producto_fecha', ['producto_id', 'fecha'], unique=False)

    op.create_table('tickets_soporte',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('agente_id', sa.Integer(), nullable=True),
    sa.Column('asunto', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('categoria', sa.Enum('RECLAMO', 'CONSULTA', 'SOPORTE_TECNICO', 'CAMBIO_DEVOLUCION', name='categoriaticket'), nullable=False),
    sa.Column('prioridad', sa.Enum('BAJA', 'MEDIA', 'ALTA', 'URGENTE', name='prioridadticket'), nullable=True),
    sa.Column('estado', sa.Enum('ABIERTO', 'EN_PROCESO', 'CERRADO', name='estadoticket'), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_cierre', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agente_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tickets_soporte', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tickets_soporte_codigo'), ['codigo'], unique=True)
        batch_op.create_index(batch_op.f('ix_tickets_soporte_fecha_creacion'), ['fecha_creacion'], unique=False)
        batch_op.create_index('ix_tickets_estado', ['estado'], unique=False)
        batch_op.create_index('ix_tickets_prioridad', ['prioridad'], unique=False)

    op.create_table('ventas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_venta', sa.String(length=20), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('vendedor_id', sa.Integer(), nullable=False),
    sa.Column('fecha_venta', sa.DateTime(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('igv', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('estado', sa.Enum('PENDIENTE', 'COMPLETADA', 'ANULADA', name='estadoventa'), nullable=False),
    sa.Column('metodo_pago', sa.Enum('EFECTIVO', 'TARJETA', 'TRANSFERENCIA', 'YAPE_PLIN', name='metodopago'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['vendedor_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ventas', schema=None) as batch_op:
        batch_op.create_index('ix_ventas_cliente_fecha', ['cliente_id', 'fecha_venta'], unique=False)
        batch_op.create_index('ix_ventas_estado_fecha', ['estado', 'fecha_venta'], unique=False)
        batch_op.create_index(batch_op.f('ix_ventas_fecha_venta'), ['fecha_venta'], unique=False)
        batch_op.create_index(batch_op.f('ix_ventas_numero_venta'), ['numero_venta'], unique=True)

    op.create_table('comentarios_ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets_soporte.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detalle_ventas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venta_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.CheckConstraint('cantidad > 0', name='ck_detalle_cantidad_positiva'),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['venta_id'], ['ventas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('detalle_ventas', schema=None) as batch_op:
        batch_op.create_index('ix_detalle_venta_id', ['venta_id'], unique=False)
        batch_op.create_index('ix_detalle_producto_id', ['producto_id'], unique=False)

    op.create_table('pedidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_pedido', sa.String(length=20), nullable=False),
    sa.Column('venta_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('direccion_envio', sa.String(length=255), nullable=False),
    sa.Column('ciudad_envio', sa.String(length=80), nullable=True),
    sa.Column('estado', sa.Enum('PROCESANDO', 'EN_CAMINO', 'ENTREGADO', 'CANCELADO', name='estadopedido'), nullable=False),
    sa.Column('transportista', sa.String(length=80), nullable=True),
    sa.Column('numero_seguimiento', sa.String(length=60), nullable=True),
    sa.Column('fecha_pedido', sa.DateTime(), nullable=True),
    sa.Column('fecha_entrega_estimada', sa.Date(), nullable=True),
    sa.Column('fecha_entrega_real', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['venta_id'], ['ventas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('venta_id')
    )
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pedidos_numero_pedido'), ['numero_pedido'], unique=True)
        batch_op.create_index('ix_pedidos_estado', ['estado'], unique=False)
        batch_op.create_index('ix_pedidos_cliente', ['cliente_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pedidos_numero_pedido'))
        batch_op.drop_index('ix_pedidos_estado')
        batch_op.drop_index('ix_pedidos_cliente')

    op.drop_table('pedidos')
    with op.batch_alter_table('detalle_ventas', schema=None) as batch_op:
        batch_op.drop_index('ix_detalle_venta_id')
        batch_op.drop_index('ix_detalle_producto_id')

    op.drop_table('detalle_ventas')
    op.drop_table('comentarios_ticket')
    with op.batch_alter_table('ventas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ventas_numero_venta'))
        batch_op.drop_index(batch_op.f('ix_ventas_fecha_venta'))
        batch_op.drop_index('ix_ventas_cliente_fecha')
        batch_op.drop_index('ix_ventas_estado_fecha')

    op.drop_table('ventas')
    with op.batch_alter_table('tickets_soporte', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tickets_soporte_fecha_creacion'))
        batch_op.drop_index(batch_op.f('ix_tickets_soporte_codigo'))
        batch_op.drop_index('ix_tickets_estado')
        batch_op.drop_index('ix_tickets_prioridad')

    op.drop_table('tickets_soporte')
    with op.batch_alter_table('movimientos_inventario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_movimientos_inventario_fecha'))
        batch_op.drop_index('ix_movimiento_producto_fecha')

    op.drop_table('movimientos_inventario')
    with op.batch_alter_table('auditoria', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auditoria_tabla_afectada'))
        batch_op.drop_index(batch_op.f('ix_auditoria_fecha'))

    op.drop_table('auditoria')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index('ix_usuarios_email_activo')
        batch_op.drop_index(batch_op.f('ix_usuarios_email'))

    op.drop_table('usuarios')
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_productos_sku'))
        batch_op.drop_index(batch_op.f('ix_productos_nombre'))
        batch_op.drop_index('ix_productos_categoria_activo')

    op.drop_table('productos')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_nombre'))

    op.drop_table('roles')
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clientes_email'))
        batch_op.drop_index(batch_op.f('ix_clientes_dni_ruc'))

    op.drop_table('clientes')
    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categorias_nombre'))

    op.drop_table('categorias')
    # ### end Alembic commands ###
